config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add extension routes here
  get '/admin/taxonomies/:taxonomy_id/taxons/:id/sort_products' => 'admin/taxons#sort_products', :as => :sort_products_taxons
  post '/admin/taxonomies/:taxonomy_id/taxons/:id/update_products' => 'admin/taxons#update_products', :as => :update_products_admin_taxonomy_taxon

end

app/models/spree/classification_decorator.rb
module Spree
  Classification.class_eval do
    attr_accessible :position
  end
end

app/models/spree/products_taxon.rb
module Spree  
  class ProductsTaxon < ActiveRecord::Base
    attr_accessible :position
    
    belongs_to :product
    belongs_to :taxon
  end
end

app/models/spree/taxon_decorator.rb
module Spree
  Taxon.class_eval do
    has_many :products, :through => :classifications, :order => 'spree_products_taxons.position'
  end
end

app/controllers/spree/admin/taxons_controller_decorator.rb
module Spree
  module Admin
    class TaxonsController < Spree::Admin::BaseController
      before_filter :load_taxon, :only => [:sort_products, :update_products]

      def sort_products
        @products = @taxon.products
      end

      def update_products
        products = @taxon.products_taxons
        product_ids_positions = params[:product_positions].split(",").map(&:to_i)
        product_ids_positions.each_with_index do |id, index|
          product = products.detect{|p| p.product_id == id }
          product.update_attributes(:position => index) unless product.nil?
        end
        redirect_to sort_products_taxons_path(@taxonomy, @taxon.id), :notice => t(:sort_products_taxons_update_message)
      end

      def load_taxon
        @taxonomy = Taxonomy.find(params[:taxonomy_id])
        @taxon = Taxon.find(params[:id])
      end
    end
  end
end

app/views/spree/admin/shared/_taxonomy_translations.html.erb
<script>
  Spree.taxonomy_translations = <%==
  { 
    :sort_products => I18n.t(:sort_products),
    :save_sorted_order => I18n.t(:save_sorted_order)
  }.to_json
%>
</script>

app/views/spree/admin/taxonomies/_sort_products_js.erb
<% content_for :head do %>
  <%= javascript_include_tag 'admin/taxon_tree_menu_overrides' %>
  <%= render :partial => 'spree/admin/shared/taxonomy_translations' %>

  <%= javascript_tag do -%>
    var initial = [
      { "attr" :
      { "id" : "<%= @taxonomy.root.id %>", "rel" : "root" },
      "data" : "<%= escape_javascript(raw(@taxonomy.root.name)) %>",
      "state" : "open",
      "children" : [
        <% @taxonomy.root.children.each_with_index do |taxon,i| %>
          {
            "attr" :
            { "id" : "<%= taxon.id %>"},
            "data" : "<%= escape_javascript(raw(taxon.name)) %>"
            <% unless taxon.children.empty? %>
              ,"state" : "closed"
            <% end %>
          }<%= ',' if i < (@taxonomy.root.children.size - 1) %>
        <% end %>
      ]
        }
    ];
  <% end -%>
<% end %>

app/views/spree/admin/taxons/sort_products.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:sort_taxon_products) %> "<%= @taxon.name %>"
<% end %>

<%= t(:sort_products_hint_message) %>

<div id="ajax_error" class="errorExplanation" style="display:none;"></div>
<% content_for :page_actions do %>
  <% # Because otherwise the form would attempt to use to_param of @taxon %>
  <% form_url = update_products_admin_taxonomy_taxon_path(@taxonomy.id, @taxon.id) %>
  <%= form_for [:update_products, :admin, @taxonomy, @taxon], :method => :post, :url => form_url do |f| %>
    <%= hidden_field_tag :taxon_id, @taxon_id %>
    <%= hidden_field_tag :product_positions, 0 %>

      <li id="save_order">
        <%= button_link_to t(:back_to_taxonomies_list), spree.admin_taxonomies_path, :icon => 'icon-arrow-left' %>
      </li>
  <% end %>
<% end %>

<ul id="products" class="thumbnails">
  <% @products.each do |product| %>
    <%= content_tag_for :li, product, :class=> "three columns", :style => 'height: 300px; list-style-type: none' do %>
      <div class="two columns thumbnail" style = "cursor: pointer;" value="<%= product.id %>">
          <%= product_image(product, :width => "145", :height => "190", :id=>"image-map") %>
          <div class="caption">
            <% product_name = product.name.split(" ") %>
            <% product_name.delete(product_name.last) %>
            <h5><%= product_name.join(" ") %></h5>
          </div>
      </div>
    <% end %>
  <% end %>
</ul>

<%= javascript_include_tag 'admin/sort_products' %>